modLoader = "javafml"
loaderVersion = "[36,)"
license = "GPLv3"

[[mods]] 
modId = "rolencrewassign" 
version = "${file.jarVersion}"
displayName = "Mine Mine no Mi: Role and Crew Assigner"
logoFile = "rolencrewassign.png"
credits = "DerHammerclock"
authors = "DerHammerclock"
description = '''
Synchronize Mine Mine no Mi data like Race, Faction and Fighting Style with your Discord Server!
Also allows you to display your crews in a Forum Channel.
'''

[[dependencies.mineminenomi]] 
modId = "mineminenomi"    
mandatory = true          
versionRange = "[0.9.5,)" 
ordering = "AFTER"
side = "SERVER"

[[dependencies.dcintegration]]
modId = "dcintegration"
mandatory = true
versionRange = "[3.0.5,)"
ordering = "AFTER"
side = "SERVER"
